fix-doc

diff --git a/sparrow b/sparrow
--- a/sparrow
+++ b/sparrow
@@ -3,7 +3,6 @@
 
 object=$1
 
-
 if test "${object}" = "plg"; then
     action=$2
     if test "${action}" = "list"; then
@@ -15,22 +14,30 @@ if test "${object}" = "plg"; then
         else
             cat plg.list
         fi
-
-
     elif test "${action}" = "install"; then
         export plg_id=$3
         mkdir -p plugins
         git_url=`perl -n -e 'chomp; next unless /\S/; @foo = split; print $foo[1] if $foo[0]=~/$ENV{plg_id}/' plg.list`
         echo "install plugin $plg_id from $git_url ... "
         git clone $git_url plugins/$plg_id
+    elif test "${action}" = "update"; then
+        export plg_id=$3
+        if test -d plugins/$plg_id; then
+            echo "updating plugin $plg_id ... "
+            cd plugins/$plg_id && git pull
+        else
+            echo "can't find plugin plugins/$plg_id"
+            exit 1
+        fi
     fi
 else
     echo "usage: sparrow project|plg action args"
-    echo "where action: list|install|create|add_site|check_site|swat_setup. and args depend on action"
+    echo "where action: create|list|install|update|add_site|check_site|swat_setup. and args depend on action"
     echo "examples:"
     echo -e "\tsparrow plg list"
     echo -e "\tsparrow plg list --local"
     echo -e "\tsparrow plg install nginx"
+    echo -e "\tsparrow plg update tomcat"
     echo -e "\tsparrow project foo create"
     echo -e "\tsparrow project foo add_plg nginx"
     echo -e "\tsparrow project foo add_plg tomcat"
